### ISSUE TITLE
this should go into opam

### ISSUE THREAD

**Issue by UnixJunkie** [tobast/ORandForest#11]
after enough testing to be sure it is doing things right

**Comment by UnixJunkie** [comment]
My tests tell that this library allows to get very powerful classifiers on real world data from chemistry.
With a forest of 3000 trees trained in parallel, I can get AUCs as high as 0.976 (a perfect classifier has an AUC of 1.0) while testing on a test set that was never seen during training.
Thanks @tobast for this very important contribution to the OCaml ecosystem (an ecosystem which is a little bit weak on the machine learning side: we would need production ready bindings to liblinear, plus a good SVM package or bindings to a very good and numerically stable SVM implementation).

**Comment by UnixJunkie** [comment]
@igarnier

**Comment by UnixJunkie** [comment]
I am relying on RF.classify_raw to be able to compute AUC values, so this recent contribution is also looking good in real world tests.

**Comment by igarnier** [comment]
This looks awesome. Thanks @tobast! And thanks François for assessing the
code on a real-world dataset :)

2017-11-30 8:09 GMT+01:00 Francois BERENGER <notifications@github.com>:

**Comment by tobast** [comment]
To be honest, I did that on my free time and never actually used it, so I'm pretty impressed that it does actually work fairly well :) I'm not anything close to proficient in machine learning either, so I'll really have trouble enhancing this. Thanks @UnixJunkie for making this software useable in the real world!

**Comment by UnixJunkie** [comment]
I use it in production, so I'd like to release it in opam.

**Comment by tobast** [comment]
@UnixJunkie If you're waiting for my opinion on this, please feel free to do so, either for this project or OC4.5; you're actually way more involved in the project than I am — which is not hard at this point :) — now, and I don't feel like you should need to contact me for this, you're definitely the maintainer now :)

**Comment by UnixJunkie** [comment]
done
