### ISSUE TITLE
a usage example would be nice

### ISSUE THREAD

**Issue by UnixJunkie** [tobast/ORandForest#2]
they also could serve as tests

**Comment by UnixJunkie** [comment]
I'd really like to use this library.
I have some sparse data that I'd like to train random forests on...

**Comment by UnixJunkie** [comment]
Anyone? @Minithorynque @tobast

**Comment by tobast** [comment]
@UnixJunkie Just as for the other issues/PRs, I'm a bit busy just right now, but I might try to put some effort back into the project in a week or two. Thanks for the interest :)

AFAIR, and dropping a quick glance to the code and documentation (available [here for OC4.5](https://tobast.fr/doc/OC4.5/) and [here for ORandForest](https://tobast.fr/doc/ORandForest/) by the way), I *think* you should (assuming you're using integers)

* First generate a dataset;
```OCaml
    let trainSet = Oc45.IntOc45.emptyTrainSet nbFeatures nbCategories featuresContinuity in
    Oc45.IntOc45.addDataList trainDataPoints trainSet
```
* then tweak the dataset to your needs;
* then turn it into a random forest;
```OCaml
    let forest = ORandForest.IntRandForest.genRandomForest nbTrees trainSet in
```
* then classify
```OCaml
    let categories = List.map (ORandForest.IntRandForest.classify forest) testDataPoints in
```

**Comment by UnixJunkie** [comment]
this could go in the README.md, since it is better than nothing and was enough for me to get started. Thanks!

**Comment by tobast** [comment]
Oh wow, I did not remember how bare the README was. That's now done. It still would benefit from a real usage example, though.

**Comment by UnixJunkie** [comment]
done
