### ISSUE TITLE
is it possible to have access to the probability to belong to each category?

### ISSUE THREAD

**Issue by UnixJunkie** [tobast/ORandForest#4]
Instead of just the category prediction.
My use case would be to rank order test examples instead of just classifying them.

**Comment by tobast** [comment]
I'd have to dive back into this old code to be sure, but AFAIR it should be no trouble

**Comment by UnixJunkie** [comment]
This issue can be labelled as a feature request. ;)
Only project members can label issues.

**Comment by UnixJunkie** [comment]
I guess there is a number of votes per class.
Maybe I can extract this value to create a probability.

**Comment by UnixJunkie** [comment]
can I become a member of this project, I'd like to play with the issue labels.
I will still send pull requests so that you can review code changes I propose.

**Comment by UnixJunkie** [comment]
related to https://github.com/tobast/ORandForest/pull/10

**Comment by tobast** [comment]
Done, please feel free to integrate whatever you think is good, I can trust you on that :) I don't have time that much to develop on this project…

**Comment by UnixJunkie** [comment]
done
